# -*- coding: utf-8 -*-
"""business_rp_simulations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1irpTefuq6MAowBD_qjKXzm_cMnj6qt89
"""

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
import os

print("Environment ready")

folders = [
    "data",
    "tables",
    "code",
    "metadata"
]

for f in folders:
    os.makedirs(f, exist_ok=True)

print("Folders created:", folders)

def generate_panel(
    endog_ai=False,
    endog_verif=False,
    meas_error=False,
    seed=123
):
    np.random.seed(seed)

    industries = ['Tech','Finance','Healthcare','Retail','Manufacturing','Energy']
    data = []

    for fid in range(1, 2501):
        firm_id = f"FIRM_{fid:04d}"
        latent_quality = np.random.normal(0, 1)

        for year in [2022, 2023, 2024, 2025]:
            base_ai = np.random.beta(2 + (year - 2022), 3)

            if endog_ai:
                ai_true = np.clip(base_ai + 0.15 * latent_quality, 0, 1)
            else:
                ai_true = base_ai

            if endog_verif:
                verif_prob = min(0.3 + 0.4 * ai_true, 0.95)
                verification = np.random.binomial(1, verif_prob)
            else:
                verification = np.random.binomial(1, 0.55)

            ai_used = ai_true
            if meas_error:
                ai_used = np.clip(ai_true + np.random.normal(0, 0.12), 0, 1)

            ceo_span = np.clip(
                np.random.normal(
                    12.4 + 2.8 * ai_true - 0.62 * ai_true * verification,
                    4.2
                ),
                5, 25
            )

            data.append({
                "firm_id": firm_id,
                "year": year,
                "industry": np.random.choice(industries),
                "ai_index": round(ai_used, 3),
                "verification": verification,
                "ceo_span": round(ceo_span, 1),
                "size_ln_assets": round(np.random.normal(8.5, 1.7), 2)
            })

    return pd.DataFrame(data)

def run_regression(df):
    df["industry_code"] = pd.Categorical(df.industry).codes

    model = smf.ols(
        "ceo_span ~ ai_index + ai_index:verification + size_ln_assets + industry_code",
        data=df
    ).fit()

    return {
        "ai_coef": model.params["ai_index"],
        "ai_se": model.bse["ai_index"],
        "interaction_coef": model.params["ai_index:verification"],
        "r2": model.rsquared,
        "n": int(model.nobs)
    }

scenarios = {
    "baseline": dict(endog_ai=False, endog_verif=False, meas_error=False),
    "endog_ai": dict(endog_ai=True, endog_verif=False, meas_error=False),
    "endog_verif": dict(endog_ai=False, endog_verif=True, meas_error=False),
    "meas_error": dict(endog_ai=False, endog_verif=False, meas_error=True)
}

results = []

for name, params in scenarios.items():
    coefs = []

    for r in range(150):
        df = generate_panel(**params, seed=100+r)
        est = run_regression(df)
        coefs.append(est["ai_coef"])

    results.append({
        "scenario": name,
        "mean_ai_coef": round(np.mean(coefs), 3),
        "bias": round(np.mean(coefs) - 2.8, 3),
        "std_dev": round(np.std(coefs), 3)
    })

summary = pd.DataFrame(results)
summary

summary.to_csv("tables/table_simulation_results.csv", index=False)

example_df = generate_panel()
example_df.head(500).to_csv("data/panel_data_example.csv", index=False)

pd.DataFrame({
    "parameter": ["True AI effect"],
    "value": [2.8]
}).to_csv("metadata/dgp_parameters.csv", index=False)

print("Files saved.")

readme_text = """
This repository contains simulation code and replication files for a synthetic business research paper studying how AI adoption alters firm decision hierarchies.

Contents:
- business_rp_simulations.ipynb: Generates all data and tables
- data/panel_data_example.csv: Example firm-level panel data
- tables/table_simulation_results.csv: Monte Carlo simulation results
- metadata/dgp_parameters.csv: True parameters used in the data-generating process

All results can be reproduced by running the notebook top to bottom.
"""

with open("README.md", "w") as f:
    f.write(readme_text.strip())

print("Clean README created.")